### ISSUE TITLE
Q: Paypal?

### ISSUE THREAD

**Issue by syberknight** [afterlight/GoalMeter#5]
does this script of yours pull in the Paypal balance & adjust the meter dynamically?

**Comment by jvdl** [comment]
It doesn't do anything automatically, it's up to you to implement your own way of filling in the numbers. either in the markup or via the JavaScript, e.g.

``` html
<div id="goal-meter-1" class="goal-meter">
    <div class="goal-meter-track">
        <div class="goal-meter-goal">
            <div class="goal-meter-amount"> YOUR_GOAL_AMOUNT_HERE </div>
        </div>
        <div class="goal-meter-progress">
            <div class="goal-meter-amount"> YOUR_CURRENT_AMOUNT_HERE  </div>
        </div>
    </div>
</div>
```

or 

``` js
$("#goal-meter").goalMeter({
    "goalAmount": 1000,
    "progressAmount": 425
});
```

**Comment by syberknight** [comment]
ah. bummer (cause i don't know how to do that). thanks for your quick reply tho!

**Comment by jvdl** [comment]
Ah yeah if you're not familiar with these types of things it can be difficult. If you've got time and want to learn, https://developer.paypal.com/ has a bunch of resources to help you out, including API documentation for how to perform various interactions with your account.

**Comment by syberknight** [comment]
cool. thanks.
